### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by alessandratrapani**

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
@alessandratrapani Let me know when this is ready for final review

**Comment by CodyCBakerPhD** [comment]
@alessandratrapani Should the `power` of a row of the `PatternedOptogeneticStimulusTable` be `power_in_W`?

**Comment by CodyCBakerPhD** [comment]
Also should `pulse_rate` be `pulse_rate_in_Hz`?

**Comment by alessandratrapani** [comment]
> Should the power of a row of the PatternedOptogeneticStimulusTable be power_in_W?
> Also should `pulse_rate` be `pulse_rate_in_Hz`?

They have an attribute that explicitly states the u.m.
Do you think I should add the u.m also in the name?

**Comment by CodyCBakerPhD** [comment]
Oh I see now, thanks for clarifying

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by CodyCBakerPhD** [comment]
LGTM

**Pull request merged**
